### ISSUE TITLE
Directory migration

### ISSUE THREAD

**Issue by danahertzberg** [danahertzberg/issues#6]
## Tasks
- [x] Send quote to Cameron

## Estimated work
- Phase 1 - Phonebook is built with Mark and linked to from directory
    - Provide CSS for phonebook to Mark
    - Migrate directory content
- Phase 2 - Phase out directory overall as a part of web governance

**Comment by danahertzberg** [comment]
## Needs for rebuild:
- [x] Search redirect onto arizona.edu
- [x] I am menu (external links)
- [x] Resources menu (external links)
- [x] Rebuild homepage
- [x] Mark rebuild phonebook as separate integration (external link on directory)
- [x] Dana send Mark CSS to use with new phonebook integration
- [x] Build out menu
- [x] New content type/views for directory content
- [x] Migrate directory content (manual or custom migration)
- [x] Enable global footer
- [x] Verify Google Analytics is as expected
- [x] Request web header - requested via email to brand@email.arizona.edu on 9/15/2023 - not needed for Directory or Phonebook

## Expected time needed - 100 hours
- 5 hours (Dana - Search, External menu/header links, Footer)
- 5 hours (Dana - Homepage rebuild)
- 15 hours (Dana - Phonebook CSS)
- 5 hours (Dana - Menu build)
- 15 hours (Dana - Custom directory content type/views)
- 55 hours (Sanjana - Migrate directory content)

**Comment by danahertzberg** [comment]
Migrate content should be done by students rather than developer

**Comment by danahertzberg** [comment]
Phonebook needs:
- Mark Felix's team can start now
- Oct 15 timeline goal (Dana and Mark)
- phonebook.arizona.edu domain redirects to directory.arizona.edu/phonebook
   - Check to ensure it's a temporary domain (Joe)

Get started needs:
- Kat connection/approval to start
- Mark connection/approval to start
- Donna approval to start
- Sanjana ensure student availability
- Quote services

**Comment by danahertzberg** [comment]
- [x] Send quote overview to leads

https://docs.google.com/document/d/1APkgGGwWoyuO9B9Dwxq-JSqVxOlJi9mSW1rP-QJ5o1g/edit

**Comment by danahertzberg** [comment]
- Django and view.js used by Mark Felix and team (David)
- Desire timeline to push back by 3 weeks
- Have headers and sidebars match between sites (perpetually)
   - Could have matched menus similar to Arizona.edu admissions
- Biggest challenge is to write search queries and deliver search results

**Comment by danahertzberg** [comment]
- Have 2-week check in meetings with Joe, Mark, David Hoover
- Joe, Mark, and David meet to sift through PHP

**Comment by danahertzberg** [comment]
- [x] Update Quote with new timeline
- [x] Schedule meeting with Kat to go over project/timeline and what to expect

**Comment by danahertzberg** [comment]
- [x] Need to schedule meeting with Genesis to go over migration results

**Comment by danahertzberg** [comment]
Students will update spreadsheet to have new tab for client review needs

**Comment by danahertzberg** [comment]
- [x] Have students reduce duplicates https://live-azs-directory.pantheonsite.io/directory-item-audit

**Comment by danahertzberg** [comment]
- [x] Give Darcy a preview of whole directory interface - directory and phonebook - meeting requested 9/26/2023
- [ ] Look into global footer update - A-Z index to Directory
- [x] Ask Kat about phonebook being separate
- [x] Provide CSS on https://phonebook-ui.test.iam.arizona.edu/

**Comment by danahertzberg** [comment]
https://uarizona.slack.com/archives/C05SUF8QJR1/p1696445515638279

**Notes from today's meeting:**

- Joe to send footer API details used on admissions
- David to remove wordmark padding in the red bar
- David to remove blue footer contact info (replace with global footer)
- Cutover is DNS ticket to repoint dns - go-live steps needed

**Goals for next meeting on 10/16/2023**

- Complete phonebook site content
- Update directory link to go to live phonebook URL

**Go-live needs - Currently scheduled for Nov. 3**

- Date for DNS cutover
- Final approval from Kat - Received
- UAnnounce memo
- Email Kat when live
- ~Update arizona.edu 404 page~

**Post go-live tasks**

- Dana to update global footer with new links
   - A-Z Index --> Directory (https://directory.arizona.edu/)
   - Phonebook --> Phonebook (https://phonebook.arizona.edu/)

**Comment by danahertzberg** [comment]
**Dana Hertzberg** [3:01 PM](https://uarizona.slack.com/archives/C05SUF8QJR1/p1697482885177819) @here Here are some notes from today's meeting.

- [@David Hoover](https://uarizona.slack.com/team/UPPCUSHNK) Will make the remaining updates above.
- [@Dana](https://uarizona.slack.com/team/U7VMXD6RG) Will work on footer updates at the app level (fonts, links, etc.) - not ready before launch.
- Not much info here on phonebook searches that would be beyond the LDAP queries. [Here is the GA dashboard](https://lookerstudio.google.com/u/0/reporting/ef02c272-afe4-4862-b4bd-8706e3436b2f/page/nbaTD?params=%7B%22df21%22:%22include%25EE%2580%25800%25EE%2580%2580IN%25EE%2580%2580directory.arizona.edu%22%7D)
- Directory sandbox site is updated to use live phonebook URL

**Next steps**

- [x] [@David Hoover](https://uarizona.slack.com/team/UPPCUSHNK) Move phonebook to production in advance - by 10/20
- [x] [@Dana](https://uarizona.slack.com/team/U7VMXD6RG) Review with Kat - Scheduled for 10/19 - Approved!
- [x] [@Dana](https://uarizona.slack.com/team/U7VMXD6RG) Develop UAnnounce memo - by 10/20
- [x] [@fischerm](https://uarizona.slack.com/team/U0SAQHERX) Get date for [pantheon.arizona.edu](http://pantheon.arizona.edu/) DNS cutover - by 10/20
- [x] [@parsonsj](https://uarizona.slack.com/team/U0D9L7ZPG) Remove domain from existing Pantheon site - Coordinate by 10/20
- [x] [@parsonsj](https://uarizona.slack.com/team/U0D9L7ZPG) Get [directory.arizona.edu](http://directory.arizona.edu/) domain transferred - Coordinate by 10/20

Work this week with hopes of having an earlier launch date of next week! :tada: (edited)

**Comment by danahertzberg** [comment]
![Image](https://github.com/danahertzberg/issues/assets/59745109/cd90dd0d-e66f-454f-96ec-35c27a966b5c)

Contact: uits-sia@list.arizona.edu
